app1/urls.py
from app1.views import *
from django.urls import path
app_name="friends"
urlpatterns=[
    path('sudheer/',sudheer,name='sudheer'),
    path('nivas/',nivas,name='nivas'),
]

url_navigation_by_using_both_generic_specfic/urls.py
from django.contrib import admin
from django.urls import path,include
import app1
from app2.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('mom/',mom,name='mom'),
    path('frnd/',frnd,name='frnd')
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.
def sudheer(request):
    return render(request,'sudheer.html')
def nivas(request):
    return render(request,'nivas.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def mom(request):
    return render(request,'mom.html')
def frnd(request):
    return render(request,'frnd.html')

templates/frnd.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>hai are i am in specfic url</h1>
        <a href="{% url 'friends:nivas' %}"><h1>when we going to meet✌️✌️</h1></a>
        <h2>we are so happy</h2>
        <a href="{% url 'mom' %}"><h1> yes we going to meet✌️✌️ today</h1></a>
    </center>
</body>
</html>

templates/mom.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>hai nanaa  how are you</h1>
        <h2>time ki tinu raa</h2>
    </center>
</body>
</html>

templates/nivas.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>hai my dear frnd by using generic</h1>
        <a href="{% url 'friends:nivas' %}"><h1>when we going to meet✌️✌️</h1></a>
        <h2>we are so happy</h2>
        <a href="{% url 'frnd' %}"><h1> yes we going to meet✌️✌️ today</h1></a>

    </center>
</body>
</html>

templates/sudheer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>hai ra mama</h1>
        <a href="{% url 'friends:nivas' %}"><h1>when we going to meet✌️✌️</h1></a>
        <h2>we are so happy</h2>
        <a href="{% url 'mom' %}"><h1> yes we going to meet✌️✌️ today</h1></a>
    </center>
</body>
</html>